<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />

<meta name="viewport" content="width=device-width, initial-scale=1" />


<meta name="date" content="2026-01-13" />

<title>Testing the Dimensions with CIFTI Files</title>

<script>// Pandoc 2.9 adds attributes on both header and div. We remove the former (to
// be compatible with the behavior of Pandoc < 2.8).
document.addEventListener('DOMContentLoaded', function(e) {
  var hs = document.querySelectorAll("div.section[class*='level'] > :first-child");
  var i, h, a;
  for (i = 0; i < hs.length; i++) {
    h = hs[i];
    if (!/^h[1-6]$/i.test(h.tagName)) continue;  // it should be a header h1-h6
    a = h.attributes;
    while (a.length > 0) h.removeAttribute(a[0].name);
  }
});
</script>

<style type="text/css">
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
</style>



<style type="text/css">
code {
white-space: pre;
}
.sourceCode {
overflow: visible;
}
</style>
<style type="text/css" data-origin="pandoc">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
{ counter-reset: source-line 0; }
pre.numberSource code > span
{ position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
{ content: counter(source-line);
position: relative; left: -1em; text-align: right; vertical-align: baseline;
border: none; display: inline-block;
-webkit-touch-callout: none; -webkit-user-select: none;
-khtml-user-select: none; -moz-user-select: none;
-ms-user-select: none; user-select: none;
padding: 0 4px; width: 4em;
color: #aaaaaa;
}
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa; padding-left: 4px; }
div.sourceCode
{ }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } 
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } 
code span.at { color: #7d9029; } 
code span.bn { color: #40a070; } 
code span.bu { color: #008000; } 
code span.cf { color: #007020; font-weight: bold; } 
code span.ch { color: #4070a0; } 
code span.cn { color: #880000; } 
code span.co { color: #60a0b0; font-style: italic; } 
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } 
code span.do { color: #ba2121; font-style: italic; } 
code span.dt { color: #902000; } 
code span.dv { color: #40a070; } 
code span.er { color: #ff0000; font-weight: bold; } 
code span.ex { } 
code span.fl { color: #40a070; } 
code span.fu { color: #06287e; } 
code span.im { color: #008000; font-weight: bold; } 
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } 
code span.kw { color: #007020; font-weight: bold; } 
code span.op { color: #666666; } 
code span.ot { color: #007020; } 
code span.pp { color: #bc7a00; } 
code span.sc { color: #4070a0; } 
code span.ss { color: #bb6688; } 
code span.st { color: #4070a0; } 
code span.va { color: #19177c; } 
code span.vs { color: #4070a0; } 
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } 
</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    var j = 0;
    while (j < rules.length) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") {
        j++;
        continue;
      }
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') {
        j++;
        continue;
      }
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>




<style type="text/css">body {
background-color: #fff;
margin: 1em auto;
max-width: 700px;
overflow: visible;
padding-left: 2em;
padding-right: 2em;
font-family: "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
font-size: 14px;
line-height: 1.35;
}
#TOC {
clear: both;
margin: 0 0 10px 10px;
padding: 4px;
width: 400px;
border: 1px solid #CCCCCC;
border-radius: 5px;
background-color: #f6f6f6;
font-size: 13px;
line-height: 1.3;
}
#TOC .toctitle {
font-weight: bold;
font-size: 15px;
margin-left: 5px;
}
#TOC ul {
padding-left: 40px;
margin-left: -1.5em;
margin-top: 5px;
margin-bottom: 5px;
}
#TOC ul ul {
margin-left: -2em;
}
#TOC li {
line-height: 16px;
}
table {
margin: 1em auto;
border-width: 1px;
border-color: #DDDDDD;
border-style: outset;
border-collapse: collapse;
}
table th {
border-width: 2px;
padding: 5px;
border-style: inset;
}
table td {
border-width: 1px;
border-style: inset;
line-height: 18px;
padding: 5px 5px;
}
table, table th, table td {
border-left-style: none;
border-right-style: none;
}
table thead, table tr.even {
background-color: #f7f7f7;
}
p {
margin: 0.5em 0;
}
blockquote {
background-color: #f6f6f6;
padding: 0.25em 0.75em;
}
hr {
border-style: solid;
border: none;
border-top: 1px solid #777;
margin: 28px 0;
}
dl {
margin-left: 0;
}
dl dd {
margin-bottom: 13px;
margin-left: 13px;
}
dl dt {
font-weight: bold;
}
ul {
margin-top: 0;
}
ul li {
list-style: circle outside;
}
ul ul {
margin-bottom: 0;
}
pre, code {
background-color: #f7f7f7;
border-radius: 3px;
color: #333;
white-space: pre-wrap; 
}
pre {
border-radius: 3px;
margin: 5px 0px 10px 0px;
padding: 10px;
}
pre:not([class]) {
background-color: #f7f7f7;
}
code {
font-family: Consolas, Monaco, 'Courier New', monospace;
font-size: 85%;
}
p > code, li > code {
padding: 2px 0px;
}
div.figure {
text-align: center;
}
img {
background-color: #FFFFFF;
padding: 2px;
border: 1px solid #DDDDDD;
border-radius: 3px;
border: 1px solid #CCCCCC;
margin: 0 5px;
}
h1 {
margin-top: 0;
font-size: 35px;
line-height: 40px;
}
h2 {
border-bottom: 4px solid #f7f7f7;
padding-top: 10px;
padding-bottom: 2px;
font-size: 145%;
}
h3 {
border-bottom: 2px solid #f7f7f7;
padding-top: 10px;
font-size: 120%;
}
h4 {
border-bottom: 1px solid #f7f7f7;
margin-left: 8px;
font-size: 105%;
}
h5, h6 {
border-bottom: 1px solid #ccc;
font-size: 105%;
}
a {
color: #0033dd;
text-decoration: none;
}
a:hover {
color: #6666ff; }
a:visited {
color: #800080; }
a:visited:hover {
color: #BB00BB; }
a[href^="http:"] {
text-decoration: underline; }
a[href^="https:"] {
text-decoration: underline; }

code > span.kw { color: #555; font-weight: bold; } 
code > span.dt { color: #902000; } 
code > span.dv { color: #40a070; } 
code > span.bn { color: #d14; } 
code > span.fl { color: #d14; } 
code > span.ch { color: #d14; } 
code > span.st { color: #d14; } 
code > span.co { color: #888888; font-style: italic; } 
code > span.ot { color: #007020; } 
code > span.al { color: #ff0000; font-weight: bold; } 
code > span.fu { color: #900; font-weight: bold; } 
code > span.er { color: #a61717; background-color: #e3d2d2; } 
</style>




</head>

<body>




<h1 class="title toc-ignore">Testing the Dimensions with CIFTI
Files</h1>
<h4 class="date">2026-01-13</h4>



<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" tabindex="-1"></a>install_dir <span class="ot">=</span> <span class="fu">tempfile</span>()</span>
<span id="cb1-2"><a href="#cb1-2" tabindex="-1"></a><span class="fu">dir.create</span>(install_dir)</span></code></pre></div>
<div id="load-msc-data-and-test-data-from-cifti-package" class="section level1">
<h1>Load MSC data and test data from cifti package</h1>
<p>Using <code>download_cifti_data()</code> and
<code>download.file</code> to download the test data.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" tabindex="-1"></a><span class="fu">library</span>(cifti)</span>
<span id="cb2-2"><a href="#cb2-2" tabindex="-1"></a><span class="fu">download_cifti_data</span>(<span class="at">outdir =</span> install_dir)</span></code></pre></div>
<pre><code>## [1] &quot;/var/folders/1s/wrtqcpxn685_zk570bnx9_rr0000gr/T//RtmpOoSPG4/filee204e8eb9b/cifti-2_test_data/ones.dscalar.nii&quot;                                     
## [2] &quot;/var/folders/1s/wrtqcpxn685_zk570bnx9_rr0000gr/T//RtmpOoSPG4/filee204e8eb9b/cifti-2_test_data/Conte69.MyelinAndCorrThickness.32k_fs_LR.dscalar.nii&quot; 
## [3] &quot;/var/folders/1s/wrtqcpxn685_zk570bnx9_rr0000gr/T//RtmpOoSPG4/filee204e8eb9b/cifti-2_test_data/Conte69.R.inflated.32k_fs_LR.surf.gii&quot;                
## [4] &quot;/var/folders/1s/wrtqcpxn685_zk570bnx9_rr0000gr/T//RtmpOoSPG4/filee204e8eb9b/cifti-2_test_data/Conte69.L.inflated.32k_fs_LR.surf.gii&quot;                
## [5] &quot;/var/folders/1s/wrtqcpxn685_zk570bnx9_rr0000gr/T//RtmpOoSPG4/filee204e8eb9b/cifti-2_test_data/Conte69_AverageT1w_restore.nii.gz&quot;                    
## [6] &quot;/var/folders/1s/wrtqcpxn685_zk570bnx9_rr0000gr/T//RtmpOoSPG4/filee204e8eb9b/cifti-2_test_data/Conte69.MyelinAndCorrThickness.32k_fs_LR.ptseries.nii&quot;
## [7] &quot;/var/folders/1s/wrtqcpxn685_zk570bnx9_rr0000gr/T//RtmpOoSPG4/filee204e8eb9b/cifti-2_test_data/Conte69.parcellations_VGD11b.32k_fs_LR.dlabel.nii&quot;    
## [8] &quot;/var/folders/1s/wrtqcpxn685_zk570bnx9_rr0000gr/T//RtmpOoSPG4/filee204e8eb9b/cifti-2_test_data/Conte69.MyelinAndCorrThickness.32k_fs_LR.dtseries.nii&quot;</code></pre>
<p>Here we will download a NIfTI file from the MSC dataset:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" tabindex="-1"></a>mscfile <span class="ot">=</span> <span class="fu">file.path</span>(</span>
<span id="cb4-2"><a href="#cb4-2" tabindex="-1"></a>  install_dir, </span>
<span id="cb4-3"><a href="#cb4-3" tabindex="-1"></a>  <span class="st">&quot;sub-MSC01_ses-func01_task-rest_bold_32k_fsLR.dtseries.nii&quot;</span>)</span>
<span id="cb4-4"><a href="#cb4-4" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">file.exists</span>(mscfile)) {</span>
<span id="cb4-5"><a href="#cb4-5" tabindex="-1"></a>  <span class="co"># url = paste0(</span></span>
<span id="cb4-6"><a href="#cb4-6" tabindex="-1"></a>  <span class="co">#   &quot;https://openneuro.org/crn/datasets/ds000224/snapshots/00002/files/&quot;, </span></span>
<span id="cb4-7"><a href="#cb4-7" tabindex="-1"></a>  <span class="co">#   &quot;derivatives:&quot;, &quot;surface_pipeline:&quot;, &quot;sub-MSC01:&quot;,</span></span>
<span id="cb4-8"><a href="#cb4-8" tabindex="-1"></a>  <span class="co">#   &quot;processed_restingstate_timecourses:&quot;,  &quot;ses-func01:cifti:&quot;,</span></span>
<span id="cb4-9"><a href="#cb4-9" tabindex="-1"></a>  <span class="co">#   &quot;sub-MSC01_ses-func01_task-rest_bold_32k_fsLR.dtseries.nii&quot;)</span></span>
<span id="cb4-10"><a href="#cb4-10" tabindex="-1"></a>  url <span class="ot">=</span> <span class="fu">paste0</span>(<span class="st">&quot;https://s3.amazonaws.com/openneuro/ds000224/ds000224_R1.0.2/&quot;</span>,</span>
<span id="cb4-11"><a href="#cb4-11" tabindex="-1"></a>               <span class="st">&quot;uncompressed/derivatives/surface_pipeline/sub-MSC01/&quot;</span>, </span>
<span id="cb4-12"><a href="#cb4-12" tabindex="-1"></a>               <span class="st">&quot;processed_restingstate_timecourses/ses-func01/cifti/&quot;</span>, </span>
<span id="cb4-13"><a href="#cb4-13" tabindex="-1"></a>               <span class="st">&quot;sub-MSC01_ses-func01_task-rest_bold_32k_fsLR.dtseries.nii&quot;</span>)</span>
<span id="cb4-14"><a href="#cb4-14" tabindex="-1"></a>  res <span class="ot">=</span> <span class="fu">download.file</span>(<span class="at">url =</span> url, </span>
<span id="cb4-15"><a href="#cb4-15" tabindex="-1"></a>    <span class="at">destfile =</span> mscfile, <span class="at">mode =</span> <span class="st">&quot;wb&quot;</span>)</span>
<span id="cb4-16"><a href="#cb4-16" tabindex="-1"></a>  <span class="fu">stopifnot</span>(<span class="fu">file.exists</span>(mscfile))</span>
<span id="cb4-17"><a href="#cb4-17" tabindex="-1"></a>}</span></code></pre></div>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" tabindex="-1"></a>test_dir <span class="ot">=</span> <span class="fu">file.path</span>(install_dir, <span class="st">&quot;cifti-2_test_data&quot;</span>)</span>
<span id="cb5-2"><a href="#cb5-2" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" tabindex="-1"></a>ds <span class="ot">&lt;-</span> <span class="fu">read_cifti</span>(</span>
<span id="cb5-4"><a href="#cb5-4" tabindex="-1"></a>  <span class="fu">file.path</span>(test_dir,</span>
<span id="cb5-5"><a href="#cb5-5" tabindex="-1"></a>            <span class="st">&quot;Conte69.MyelinAndCorrThickness.32k_fs_LR.dscalar.nii&quot;</span>)</span>
<span id="cb5-6"><a href="#cb5-6" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## Parsing Volume Data</code></pre>
<pre><code>## Parsing Surface Data</code></pre>
<pre><code>## Parsing Parcel Data</code></pre>
<pre><code>## Parsing Named Map Data</code></pre>
<pre><code>## Parsing Brain Model Data</code></pre>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" tabindex="-1"></a>dt <span class="ot">&lt;-</span> <span class="fu">read_cifti</span>(</span>
<span id="cb11-2"><a href="#cb11-2" tabindex="-1"></a>  <span class="fu">file.path</span>(test_dir,</span>
<span id="cb11-3"><a href="#cb11-3" tabindex="-1"></a>            <span class="st">&quot;Conte69.MyelinAndCorrThickness.32k_fs_LR.dtseries.nii&quot;</span>)</span>
<span id="cb11-4"><a href="#cb11-4" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## Parsing Volume Data</code></pre>
<pre><code>## Parsing Surface Data</code></pre>
<pre><code>## Parsing Parcel Data</code></pre>
<pre><code>## Parsing Named Map Data</code></pre>
<pre><code>## Parsing Brain Model Data</code></pre>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" tabindex="-1"></a>pt <span class="ot">&lt;-</span> <span class="fu">read_cifti</span>(</span>
<span id="cb17-2"><a href="#cb17-2" tabindex="-1"></a>  <span class="fu">file.path</span>(test_dir,</span>
<span id="cb17-3"><a href="#cb17-3" tabindex="-1"></a>            <span class="st">&quot;Conte69.MyelinAndCorrThickness.32k_fs_LR.ptseries.nii&quot;</span>)</span>
<span id="cb17-4"><a href="#cb17-4" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## Parsing Volume Data</code></pre>
<pre><code>## Parsing Surface Data</code></pre>
<pre><code>## Parsing Parcel Data</code></pre>
<pre><code>## Parsing Named Map Data</code></pre>
<pre><code>## Parsing Brain Model Data</code></pre>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" tabindex="-1"></a>dl <span class="ot">&lt;-</span> <span class="fu">read_cifti</span>(</span>
<span id="cb23-2"><a href="#cb23-2" tabindex="-1"></a>  <span class="fu">file.path</span>(test_dir, </span>
<span id="cb23-3"><a href="#cb23-3" tabindex="-1"></a>            <span class="st">&quot;Conte69.parcellations_VGD11b.32k_fs_LR.dlabel.nii&quot;</span>) </span>
<span id="cb23-4"><a href="#cb23-4" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## Parsing Volume Data</code></pre>
<pre><code>## Parsing Surface Data</code></pre>
<pre><code>## Parsing Parcel Data</code></pre>
<pre><code>## Parsing Named Map Data</code></pre>
<pre><code>## Parsing Brain Model Data</code></pre>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" tabindex="-1"></a>msc <span class="ot">&lt;-</span> <span class="fu">read_cifti</span>(mscfile, <span class="at">trans_data =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## Parsing Volume Data</code></pre>
<pre><code>## Parsing Surface Data</code></pre>
<pre><code>## Parsing Parcel Data</code></pre>
<pre><code>## Parsing Named Map Data</code></pre>
<pre><code>## Parsing Brain Model Data</code></pre>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" tabindex="-1"></a>msc_trans <span class="ot">&lt;-</span> <span class="fu">read_cifti</span>(mscfile, <span class="at">trans_data =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## Parsing Volume Data</code></pre>
<pre><code>## Parsing Surface Data</code></pre>
<pre><code>## Parsing Parcel Data</code></pre>
<pre><code>## Parsing Named Map Data</code></pre>
<pre><code>## Parsing Brain Model Data</code></pre>
<div id="for-reference-msc-01-65890-818-using-matlab-ft_read_cifti-showing-first-5-rows-columns" class="section level2">
<h2>For reference: MSC 01 (65890 * 818) (using matlab ft_read_cifti),
showing first 5 rows &amp; columns</h2>
<pre><code>##            V1       V2       V3       V4       V5
## [1,]  1.60060  2.27580  1.60540  0.12593 -0.49364
## [2,]  1.85790  2.55780  1.59500 -0.84614 -2.63840
## [3,]  0.33651  1.46200  1.77790  0.34857 -1.93580
## [4,]  0.95052  0.71743 -0.94483 -2.33310 -2.10040
## [5,] -2.08590 -1.99750 -1.24970 -0.93712 -0.58043</code></pre>
</div>
<div id="msc-sub-01-session-1-sub-msc01_ses-func01_task-rest_bold_32k_fslr.dtseries.nii" class="section level2">
<h2>MSC Sub-01 Session 1
(sub-MSC01_ses-func01_task-rest_bold_32k_fsLR.dtseries.nii)</h2>
<p><code>read_cifti(fname = , trans_data = FALSE)</code> * header
dimension shows 65890 * 818 * read in file shows 65890 * 818 by setting
trans_data to <em>FALSE</em></p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" tabindex="-1"></a>msc<span class="sc">$</span>hdr</span></code></pre></div>
<pre><code>## NIfTI-1 format
##   Type            : nifti
##   Data Type       : 16 (FLOAT32)
##   Bits per Pixel  : 32
##   Slice Code      : 0 (Unknown)
##   Intent Code     : 3002 ()
##   Qform Code      : 0 (Unknown)
##   Sform Code      : 0 (Unknown)
##   Dimension       : 1 x 1 x 1 x 1 x 65890 x 818
##   Pixel Dimension : 1 x 1 x 1 x 1 x 1 x 1
##   Voxel Units     :
##   Time Units      : sec</code></pre>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" tabindex="-1"></a><span class="fu">dim</span>(msc<span class="sc">$</span>data)</span></code></pre></div>
<pre><code>## [1] 65890   818</code></pre>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" tabindex="-1"></a>msc<span class="sc">$</span>data[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>]</span></code></pre></div>
<pre><code>##           [,1]      [,2]      [,3]      [,4]      [,5]
## [1,]  1.600599  2.275847  1.605402  0.125929 -0.493640
## [2,]  1.857941  2.557801  1.595005 -0.846137 -2.638434
## [3,]  0.336508  1.461959  1.777888  0.348566 -1.935833
## [4,]  0.950522  0.717431 -0.944832 -2.333094 -2.100426
## [5,] -2.085948 -1.997536 -1.249652 -0.937115 -0.580428</code></pre>
<ul>
<li>If transpose is not set to <em>FALSE</em> (default is
<em>TRUE</em>), it will return a 818 * 65890 that is filled correctly,
and user just have to <code>t()</code> the <code>cii$data</code></li>
</ul>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" tabindex="-1"></a><span class="fu">t</span>(msc_trans<span class="sc">$</span>data[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>])</span></code></pre></div>
<pre><code>##           [,1]      [,2]      [,3]      [,4]      [,5]
## [1,]  1.600599  2.275847  1.605402  0.125929 -0.493640
## [2,]  1.857941  2.557801  1.595005 -0.846137 -2.638434
## [3,]  0.336508  1.461959  1.777888  0.348566 -1.935833
## [4,]  0.950522  0.717431 -0.944832 -2.333094 -2.100426
## [5,] -2.085948 -1.997536 -1.249652 -0.937115 -0.580428</code></pre>
</div>
<div id="data-where-dimensions-are-row-x-dense-loads-fine.-updated-function-loads-them-the-same-way-as-before." class="section level2">
<h2>Data where dimensions are row x dense loads fine. Updated function
loads them the same way as before.</h2>
<div id="conte69.myelinandcorrthickness.32k_fs_lr.dscalar.nii" class="section level3">
<h3>Conte69.MyelinAndCorrThickness.32k_fs_LR.dscalar.nii</h3>
<ul>
<li>Dense file “d”, vertex level data</li>
<li>Header shows dimension as rows * dense</li>
</ul>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" tabindex="-1"></a>ds<span class="sc">$</span>hdr</span></code></pre></div>
<pre><code>## NIfTI-1 format
##   Type            : nifti
##   Data Type       : 16 (FLOAT32)
##   Bits per Pixel  : 32
##   Slice Code      : 0 (Unknown)
##   Intent Code     : 3006 ()
##   Qform Code      : 0 (Unknown)
##   Sform Code      : 0 (Unknown)
##   Dimension       : 1 x 1 x 1 x 1 x 2 x 60951
##   Pixel Dimension : 1 x 1 x 1 x 1 x 1 x 1
##   Voxel Units     :
##   Time Units      : sec</code></pre>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" tabindex="-1"></a><span class="fu">attributes</span>(ds<span class="sc">$</span>BrainModel[[<span class="dv">1</span>]])</span></code></pre></div>
<pre><code>## $IndexOffset
## [1] 0
## 
## $IndexCount
## [1] 30424
## 
## $BrainStructure
## [1] &quot;CIFTI_STRUCTURE_CORTEX_LEFT&quot;
## 
## $ModelType
## [1] &quot;CIFTI_MODEL_TYPE_SURFACE&quot;
## 
## $SurfaceNumberOfVertices
## [1] 32492</code></pre>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" tabindex="-1"></a><span class="fu">attributes</span>(ds<span class="sc">$</span>BrainModel[[<span class="dv">2</span>]])</span></code></pre></div>
<pre><code>## $IndexOffset
## [1] 30424
## 
## $IndexCount
## [1] 30527
## 
## $BrainStructure
## [1] &quot;CIFTI_STRUCTURE_CORTEX_RIGHT&quot;
## 
## $ModelType
## [1] &quot;CIFTI_MODEL_TYPE_SURFACE&quot;
## 
## $SurfaceNumberOfVertices
## [1] 32492</code></pre>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" tabindex="-1"></a><span class="fu">dim</span>(ds<span class="sc">$</span>data)</span></code></pre></div>
<pre><code>## [1] 60951     2</code></pre>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" tabindex="-1"></a><span class="fu">head</span>(ds<span class="sc">$</span>data)</span></code></pre></div>
<pre><code>##          [,1]     [,2]
## [1,] 1.321855 3.195882
## [2,] 1.373803 2.141433
## [3,] 1.408264 3.028383
## [4,] 1.244012 3.237031
## [5,] 1.479665 2.216135
## [6,] 1.266741 2.795304</code></pre>
</div>
<div id="conte69.myelinandcorrthickness.32k_fs_lr.dtseries.nii" class="section level3">
<h3>Conte69.MyelinAndCorrThickness.32k_fs_LR.dtseries.nii</h3>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" tabindex="-1"></a>dt<span class="sc">$</span>hdr</span></code></pre></div>
<pre><code>## NIfTI-1 format
##   Type            : nifti
##   Data Type       : 16 (FLOAT32)
##   Bits per Pixel  : 32
##   Slice Code      : 0 (Unknown)
##   Intent Code     : 3002 ()
##   Qform Code      : 0 (Unknown)
##   Sform Code      : 0 (Unknown)
##   Dimension       : 1 x 1 x 1 x 1 x 2 x 60951
##   Pixel Dimension : 1 x 1 x 1 x 1 x 1 x 1
##   Voxel Units     :
##   Time Units      : sec</code></pre>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" tabindex="-1"></a><span class="fu">attributes</span>(dt<span class="sc">$</span>BrainModel[[<span class="dv">1</span>]])</span></code></pre></div>
<pre><code>## $IndexOffset
## [1] 0
## 
## $IndexCount
## [1] 30424
## 
## $BrainStructure
## [1] &quot;CIFTI_STRUCTURE_CORTEX_LEFT&quot;
## 
## $ModelType
## [1] &quot;CIFTI_MODEL_TYPE_SURFACE&quot;
## 
## $SurfaceNumberOfVertices
## [1] 32492</code></pre>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" tabindex="-1"></a><span class="fu">attributes</span>(dt<span class="sc">$</span>BrainModel[[<span class="dv">2</span>]])</span></code></pre></div>
<pre><code>## $IndexOffset
## [1] 30424
## 
## $IndexCount
## [1] 30527
## 
## $BrainStructure
## [1] &quot;CIFTI_STRUCTURE_CORTEX_RIGHT&quot;
## 
## $ModelType
## [1] &quot;CIFTI_MODEL_TYPE_SURFACE&quot;
## 
## $SurfaceNumberOfVertices
## [1] 32492</code></pre>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" tabindex="-1"></a><span class="fu">dim</span>(dt<span class="sc">$</span>data)</span></code></pre></div>
<pre><code>## [1] 60951     2</code></pre>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" tabindex="-1"></a><span class="fu">head</span>(dt<span class="sc">$</span>data)</span></code></pre></div>
<pre><code>##          [,1]     [,2]
## [1,] 1.321855 3.195882
## [2,] 1.373803 2.141433
## [3,] 1.408264 3.028383
## [4,] 1.244012 3.237031
## [5,] 1.479665 2.216135
## [6,] 1.266741 2.795304</code></pre>
</div>
<div id="conte69.myelinandcorrthickness.32k_fs_lr.ptseries.nii" class="section level3">
<h3>Conte69.MyelinAndCorrThickness.32k_fs_LR.ptseries.nii</h3>
<ul>
<li>parcel level</li>
</ul>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" tabindex="-1"></a>pt<span class="sc">$</span>hdr</span></code></pre></div>
<pre><code>## NIfTI-1 format
##   Type            : nifti
##   Data Type       : 16 (FLOAT32)
##   Bits per Pixel  : 32
##   Slice Code      : 0 (Unknown)
##   Intent Code     : 3004 ()
##   Qform Code      : 0 (Unknown)
##   Sform Code      : 0 (Unknown)
##   Dimension       : 1 x 1 x 1 x 1 x 2 x 54
##   Pixel Dimension : 1 x 1 x 1 x 1 x 1 x 1
##   Voxel Units     :
##   Time Units      : sec</code></pre>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" tabindex="-1"></a><span class="fu">dim</span>(pt<span class="sc">$</span>data)</span></code></pre></div>
<pre><code>## [1] 54  2</code></pre>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" tabindex="-1"></a><span class="fu">head</span>(pt<span class="sc">$</span>data)</span></code></pre></div>
<pre><code>##          [,1]     [,2]
## [1,] 1.431012 2.515503
## [2,] 1.392534 2.339441
## [3,] 1.521327 2.154038
## [4,] 1.498012 1.684434
## [5,] 1.618780 2.652969
## [6,] 1.511189 2.089453</code></pre>
</div>
<div id="conte69.parcellations_vgd11b.32k_fs_lr.dlabel.nii-dense-label-on-vertex-level" class="section level3">
<h3>Conte69.parcellations_VGD11b.32k_fs_LR.dlabel.nii (dense label on
vertex level)</h3>
<ul>
<li>dense label</li>
</ul>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" tabindex="-1"></a>dl<span class="sc">$</span>hdr</span></code></pre></div>
<pre><code>## NIfTI-1 format
##   Type            : nifti
##   Data Type       : 16 (FLOAT32)
##   Bits per Pixel  : 32
##   Slice Code      : 0 (Unknown)
##   Intent Code     : 3007 ()
##   Qform Code      : 0 (Unknown)
##   Sform Code      : 0 (Unknown)
##   Dimension       : 1 x 1 x 1 x 1 x 3 x 64984
##   Pixel Dimension : 1 x 1 x 1 x 1 x 1 x 1
##   Voxel Units     :
##   Time Units      : sec</code></pre>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" tabindex="-1"></a><span class="fu">dim</span>(dl<span class="sc">$</span>data)</span></code></pre></div>
<pre><code>## [1] 64984     3</code></pre>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" tabindex="-1"></a><span class="fu">head</span>(dl<span class="sc">$</span>data)</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    0   67    0
## [2,]    0   59    0
## [3,]    8   56    0
## [4,]    8   54    0
## [5,]   14   87    0
## [6,]    0   64    0</code></pre>
</div>
</div>
</div>



<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
